### PR TITLE
Strip away version from batch request url

### LINKED ISSUE #1178: Path is parsed incorrectly on batch requests when adding full URL
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

When creating batch requests with the interface `BatchRequestStep` using full URLs, the URL is incorrectly parsed. The host name is stripped away, but the versioning remains.

Creating a batch request step with URL `https://graph.microsoft.com/v1.0/groups`, the URL on the batch request body will be `/v1.0/groups`. This leads to Graph treating the versioning like a part of the request path, and responding with error code 400  with error message "Resource not found for the segment 'v1.0'."

**Console Errors:** [Is there any console error]

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

1. Create a batch request step with url path:
```
const batchRequestStep: BatchRequestStep = {
	id: '1',
	request: new Request(`https://graph.microsoft.com/v1.0/groups`, {
		method: 'GET',
	}),
};
```

2. Create an instance of `BatchRequestContent` with the batch request step
```
const batchRequestContent = new BatchRequestContent([batchRequestStep]);
````

3. Retrieve the content and log out the URL
````
const batchRequestBody = await batchRequestContent.getContent();
console.log(batchRequestBody.requests[0].url); 
````

**Expected behavior:** URL is parsed to `/groups`

**Actual behavior:** URL is parsed to `/v1.0/groups`

## Usage Information
SDK Version - [SDK version you are using]

-   [x] Node (Check, if using Node version of SDK)

> Node Version - v16.14.0

### PR DESCRIPTION
**Pull request by ghandeland**
## Motivation

In node 18, the `Request` object from the fetch API will throw an error if a full URL is not supplied. Using batch requests will not work unless supplying full Graph URLs including host name, like so: `https://graph.microsoft.com/v1.0/groups`. When using the SDK with batch requests this way, I discovered that the URL is not parsed correctly, as explained in #1178.

To be able to use this functionality right now, the developer is required to enter an incorrect path, excluding the versioning.

## Test plan

[I added a test](https://github.com/microsoftgraph/msgraph-sdk-javascript/pull/1179/commits/9b1c5630f6f3489f072e33996f7cfc69444032ba) ensuring that the URL is parsed correctly.

All tests pass running `npm run test`.

## Closing issues

Fixes #1178

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [x] I have read the **CONTRIBUTING** document.
-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ghandeland** [comment]
@microsoft-github-policy-service agree


fre. 17. feb. 2023 kl. 13:21 skrev microsoft-github-policy-service[bot] <
***@***.***>:

File: src/content/BatchRequestContent.ts [hunk 1]
```diff
@@ -198,9 +198,25 @@ export class BatchRequestContent {
...
+			// Strip away version
+			const endOfVersionStrPos = path.indexOf("/");
+			if (endOfVersionStrPos !== -1) {
+				path = path.substring(endOfVersionStrPos, path.length);
+			}
+
+			requestData.url = path;
+		} else {
+			requestData.url = request.url;
+		}
```
Comment (baywet) [inline src/content/BatchRequestContent.ts:218]:
```suggestion
		requestData.url = request.url.replace(/^(?:http)?s?:?(?:\/\/)?[^\/]+\/(?:v1.0|beta)?/i, ''); // replaces <scheme>?<?>?<//><hostname:port>+</>?<version>+ by an empty string
```

What do you think of this instead? fewer allocs and conditional blocks

**Review by baywet — CHANGES_REQUESTED** [review]
Thanks for the contirbution!

File: src/content/BatchRequestContent.ts (hunk 1 above)
Comment (ghandeland) [reply src/content/BatchRequestContent.ts]: That looks good!

**Review by baywet — APPROVED** [review]
Thanks for accepting the suggestion. @koros for final review and merge please.

**Comment by ghandeland** [comment]
> Thanks for accepting the suggestion. @koros for final review and merge please.

Any progress on the final review?:)

**Comment by sebastienlevert** [comment]
Thanks for the nudge! We are currently heads down in the design of the v4 of this library so this one slipped. Though, it's an important one AFAIK so I'll mention @koros for the final checks and merge here!

**Review by koros — APPROVED** [review]
