### PR TITLE
Anwieser/middleware map change

### LINKED ISSUE #180: Minification causes issues
# Bug Report
If you try to build a release build of the react sample in Microsoft-graph-toolkit, the minification causes login not to work from this package.  This would be the same with any sample that uses minification of this package.

## Prerequisites

-   [X] Can you reproduce the problem?
-   [X] Are you running the latest version?
-   [X] Are you reporting to the correct repository?
-   [X] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Minification causes the use of Object.name to return similar values across the project.  This renders the use of that idiom ineffective.

## Steps to Reproduce

1. Start with Microsoft-graph-toolkit react sample
2. Insert your app Id, and change provider to use msalProvider
3. Try to login.  It won't work.

**Expected behavior:** It should work.

**Actual behavior:** The minified version uses the AuthenticationProviderOptions as a TelemetryHandlerOptions.

## Additional context

None

### PR DESCRIPTION
**Pull request by WieserSoftware**
A similar PR may already be submitted! Please search among the [Pull request](https://github.com/microsoftgraph/msgraph-sdk-javascript/pulls) before creating one.

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request.

**NOTE: PR's will be accepted only in case of appropriate information is provided below**

## Summary

Stop using Object.name to generate a name for looking up objects in a map, and instead switch to a Function, which is not affected by minification

## Motivation

The release build of the react-app sample from @microsoft/mgt does not function correctly with the MSAL provider. 

## Test plan

Rebuilt msgraph-sdk-javascript and Microsoft-graph-toolkit locally, and then rebuilt the sample app with my own client id.  All previous tests passed.

## Closing issues

closes #180 

Fixes #180

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [x] I have read the **CONTRIBUTING** document.
-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

File: src/middleware/MiddlewareControl.ts [hunk 1]
```diff
@@ -43,8 +45,9 @@ export class MiddlewareControl {
 	 * @param {string} name - The class name of the strongly typed option class
```
Comment (muthurathinam) [inline src/middleware/MiddlewareControl.ts]: Change the param type and name in JSDoc comment

Comment (muthurathinam) [reply src/middleware/MiddlewareControl.ts]: same applies to line no 56.
