### PR TITLE
LargeFileUpload - node  js stream support and  progress handling,  rollup library updates

### LINKED ISSUE #320: Node.js stream support missing in LargFileUploadTask
# Bug Report

## Prerequisites

-   [ x ] Can you reproduce the problem?
-   [ x ] Are you running the latest version?
-   [ x ] Are you reporting to the correct repository?
-   [ x ] Did you perform a cursory search?
        yes, I found a gist that suggested reading entire file into memory for each chunk splicing :)

## Description

Attempting to pass a Stream into LargeFileUploadTask as file content is failing with
```
this.file.content.slice is not a function
```

```js
const fileObject = {
    size,
    content: fileStream,
    name: targetFileName,
  };
  const uploadTask = await new LargeFileUploadTask(
    graphClient,
    fileObject,
    uploadSession
  );
  const response = await uploadTask.upload()
```

## Steps to Reproduce

1. Take the example https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/HEAD/docs/tasks/LargeFileUploadTask.md
2. use `var readStream = fs.createReadStream(filename);` to get a file stream and pass that in as content

**Expected behavior:** [What you expected to happen]

Stream flows and gets accumulated into chunks that get uploaded

**Actual behavior:** [What actually happened]

Error stemming from the assumption content is a Buffer

## Additional Context

Streams allow for a container limited to 100MB of RM to upload a multi GB file successfully. 
LargFileUploadTask is where it breaks.

Users of the SDK can't afford to load the entire file into RAM if they're building a multi tenant web app.

I'm willing to contribute a solution if I get someone from the maintainers to help me out (I have little experience using TypeScript and typing a stream is difficult)

## Usage Information

SDK Version - [SDK version you are using]

-   [ x ] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]

10+ (I used multiple)
 
[AB#7546](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7546)

### PR DESCRIPTION
**Pull request by nikithauc**
Fixes #320 , #305, #380 .

* Introducing new classes `StreamUpload` and `FileUpload` implementing the `FileObject` interface and having the `sliceFile` logic.
* Added a `Progress` interface for  progress handling.
* Updates roll up libraries, added copyright.

### CODE REVIEW

File: test/node/tasks/StreamUpload.ts [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+
+		const upload = new StreamUpload(readStream, fileName, totalsize);
+
+		const slice = await upload.sliceFile({ minValue: 0, maxValue: sliceSize - 1 });
+		assert.isDefined(slice);
+		assert.equal(sliceSize, (slice as Buffer).length);
+	});
+
+	it("Stream size greater than upload range size", async () => {
+		const fileName = "sample_image.jpg";
```
Comment (zengin) [inline test/node/tasks/StreamUpload.ts:32]: available from outer scope.
```suggestion
```

File: test/node/tasks/StreamUpload.ts [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+
+		const upload = new StreamUpload(readStream, fileName, totalsize);
+
+		const slice = await upload.sliceFile({ minValue: 0, maxValue: sliceSize - 1 });
+		assert.isDefined(slice);
+		assert.equal(sliceSize, (slice as Buffer).length);
+	});
+
+	it("Stream size with complete file and greater than upload range size", async () => {
+		const fileName = "sample_image.jpg";
```
Comment (zengin) [inline test/node/tasks/StreamUpload.ts:44]: available from outer scope.
```suggestion
```

File: test/node/tasks/StreamUpload.ts [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+
+import "isomorphic-fetch";
+
+import { assert } from "chai";
+import * as fs from "fs";
+
+import { StreamUpload } from "../../../src/tasks/FileUploadUtil/FileObjectClasses/StreamUpload";
+
+describe("StreamUpload", () => {
+	const fileName = "sample_image.jpg";
```
Comment (zengin) [inline test/node/tasks/StreamUpload.ts:16]: nit: define filePath once and use it everywhere.
```suggestion
	const fileName = "sample_image.jpg";
	const filePath = `./test/sample_files/${fileName}`;
```

File: test/common/tasks/LargeFileUploadTask.ts [hunk 4]
```diff
@@ -147,90 +133,244 @@ describe("LargeFileUploadTask.ts", () => {
...
-			moq.expects("uploadSliceGetRawResponse").resolves(rawResponse);
-			const result = await uploadTask.upload();
-			assert.isDefined(result);
-			assert.instanceOf(result, UploadResult);
-			assert.equal(result["location"], location);
-			const responseBody = result["responseBody"];
-			assert.isDefined(responseBody);
-			assert.equal(responseBody["id"], "TEST_ID");
+		describe("Should return a Upload Result object after a completed task with 200 status and body", () => {
+			it("Test with completed progress callback", async () => {
```
Comment (zengin) [inline test/common/tasks/LargeFileUploadTask.ts:224]: naming convention:
I did some reading, and it looks like `describe()` blocks take objects or function names and `it()` blocks take an expected action, e.g. `should call completed callback`. I think existing tests from this file are also following this convention.

Some reference documents:
https://sinonjs.org/releases/v9.2.4/stubs/
https://www.sitepoint.com/sinon-tutorial-javascript-testing-mocks-spies-stubs/

**Review by zengin — CHANGES_REQUESTED** [review]

File: docs/tasks/LargeFileUploadTask.md [hunk 5]
```diff
@@ -1,84 +1,142 @@
...
-			.then((response) => {
-				console.log(response);
-				console.log("File Uploaded Successfully.!!");
-			})
-			.catch((error) => {
-				throw err;
-			});
-	});
-}
+		const progressCallBack: Progress = {
```
Comment (baywet) [inline docs/tasks/LargeFileUploadTask.md:116]: nit: indent

File: docs/tasks/LargeFileUploadTask.md [hunk 6]
```diff
@@ -1,84 +1,142 @@
...
+		const fileObject = new StreamUpload(readStream, fileName, totalsize);
+		or
+		const readFile = fs.readFileSync(`./fileName`);
+		const fileObject = new FileUpload(readStream, fileName, totalsize);
+
+		const uploadTask = await OneDriveLargeFileUploadTask.createTaskWithFileObject(client, fileObject, options);
+		const uploadResult:UploadResult = await uploadTask.upload();
 }
 ```
+**Note - The `OneDriveLargeFileUploadTask.createTaskWithFileObject` also handles the upload session creation.**
```
Comment (baywet) [inline docs/tasks/LargeFileUploadTask.md:139]: notes are usually prefixed with `> Note: ` in the doc. It'd be nice to align. Also, there is a difference of style between here and above `*** Note: ***`.  Please align styles

File: docs/tasks/LargeFileUploadTask.md [hunk 7]
```diff
@@ -1,84 +1,142 @@
...
-		throw err;
-	}
+* To create the LargeFileUploadTask object you need to create -
+    *  An upload session as shown above.
+    *  A `FileObject` instance.
+
+**FileObject Interface**
+```typescript
+export interface FileObject {
+	content: any;
```
Comment (baywet) [inline docs/tasks/LargeFileUploadTask.md:49]:
```suggestion
	content: ArrayBuffer | Blob | Buffer;
```

File: src/tasks/FileUploadUtil/FileObjectClasses/FileUpload.ts [hunk 8]
```diff
@@ -0,0 +1,62 @@
...
+
+	/**
+	 * @public
+	 * @constructor
+	 * @param {ArrayBuffer | Blob | Buffer} content - The file to be uploaded
+	 * @param {string} name - The name of the file to be uploaded
+	 * @param {number} size - The total size of the file to be uploaded
+	 * @returns An instance of the FileUpload class
+	 */
+	public constructor(content: ArrayBuffer | Blob | Buffer, name: string, size: number) {
```
Comment (baywet) [inline src/tasks/FileUploadUtil/FileObjectClasses/FileUpload.ts:44]:
```suggestion
	public constructor(public content: ArrayBuffer | Blob | Buffer, public name: string, public size: number) {
```
With that you can remove the props declaration above and the assignment below. keep the defensive programing though.

File: src/tasks/FileUploadUtil/FileObjectClasses/FileUpload.ts [hunk 9]
```diff
@@ -0,0 +1,62 @@
...
+		this.size = size;
+	}
+
+	/**
+	 * @public
+	 * Slices the file content to the given range
+	 * @param {Range} range - The range value
+	 * @returns The sliced file part
+	 */
+	public async sliceFile(range: Range): Promise<ArrayBuffer | Blob | Buffer> {
```
Comment (baywet) [inline src/tasks/FileUploadUtil/FileObjectClasses/FileUpload.ts:59]:
```suggestion
	public sliceFile(range: Range): Promise<ArrayBuffer | Blob | Buffer> {
```
no need for async if there's no await in the body, and no need for await in the body for a single instruction

File: src/tasks/FileUploadUtil/FileObjectClasses/StreamUpload.ts [hunk 10]
```diff
@@ -0,0 +1,82 @@
+import { Readable } from "stream";
+
+import { GraphClientError } from "../../../GraphClientError";
+import { Range } from "../../../Range";
+import { FileObject } from "../../LargeFileUploadTask";
+export class StreamUpload implements FileObject {
+	content: Readable;
+	name: string;
+	size: number;
+	public constructor(content: Readable, name: string, size: number) {
```
Comment (baywet) [inline src/tasks/FileUploadUtil/FileObjectClasses/StreamUpload.ts:10]: same comment as the file upload

File: src/tasks/FileUploadUtil/FileObjectClasses/StreamUpload.ts [hunk 11]
```diff
@@ -0,0 +1,82 @@
...
+	 * Slices the file content to the given range
+	 * @param {Range} range - The range value
+	 * @returns The sliced file part
+	 */
+	public async sliceFile(range: Range): Promise<ArrayBuffer | Blob | Buffer> {
+		const rangeSize = range.maxValue - range.minValue + 1;
+		/* readable.readable Is true if it is safe to call readable.read(),
+		 * which means the stream has not been destroyed or emitted 'error' or 'end'
+		 */
+		if (this.content.readable) {
```
Comment (baywet) [inline src/tasks/FileUploadUtil/FileObjectClasses/StreamUpload.ts:30]: as the content property is public (default in typescript), someone could set it as null/undefined and this would derail.
You need to either change the access modifier, or add a readonly, or defend here.

File: src/tasks/FileUploadUtil/FileObjectClasses/StreamUpload.ts [hunk 12]
```diff
@@ -0,0 +1,82 @@
...
+	 * @param {number} size - The size of bytes to be read
+	 * @returns Buffer with the given length of data.
+	 */
+
+	private readNBytesFromStream(size: number): Promise<Buffer> {
+		return new Promise((resolve, reject) => {
+			const chunks = [];
+			let remainder = size;
+			let length = 0;
+			this.content.on("end", () => {
```
Comment (baywet) [inline src/tasks/FileUploadUtil/FileObjectClasses/StreamUpload.ts:53]: same comment on content potentially being null

File: src/tasks/FileUploadUtil/Interfaces/IProgress.ts [hunk 13]
```diff
@@ -0,0 +1,26 @@
...
+import { UploadResult } from "../UploadResult";
+
+/**
+ * Interface enabling progress handling with callbacks.
+ */
+export interface Progress {
+	/**
+	 * Parameters that are passed into the progress, completed, failure callback options.
+	 */
+	extraCallbackParams?: unknown;
```
Comment (baywet) [inline src/tasks/FileUploadUtil/Interfaces/IProgress.ts:13]: shouldn't this be an array of unknown?

File: src/tasks/LargeFileUploadTask.ts [hunk 14]
```diff
@@ -65,9 +68,10 @@ export interface LargeFileUploadSession {
  * @property {number} size - Specifies size of the file
  */
 export interface FileObject {
-	content: ArrayBuffer | File;
+	content: any;
```
Comment (baywet) [inline src/tasks/LargeFileUploadTask.ts:71]: make it generic instead of having any. Having any will require consumers to do a bunch of type testing/casting.

File: src/tasks/LargeFileUploadTask.ts [hunk 15]
```diff
@@ -146,10 +150,21 @@ export class LargeFileUploadTask {
...
 	public constructor(client: Client, file: FileObject, uploadSession: LargeFileUploadSession, options: LargeFileUploadTaskOptions = {}) {
 		this.client = client;
-		this.file = file;
+
+		if (!file.sliceFile) {
+			console.warn("Please pass a fileObject instance");
+			try {
+				this.file = new FileUpload(file.content, file.name, file.size);
+			} catch (err) {
+				throw new Error("use file upload object");
```
Comment (baywet) [inline src/tasks/LargeFileUploadTask.ts:159]: maybe pass this source error into the new error so the actual issue bubbles up?

File: src/tasks/LargeFileUploadTask.ts [hunk 16]
```diff
@@ -146,10 +150,21 @@ export class LargeFileUploadTask {
...
+			}
+		} else {
+			this.file = file;
+		}
 		if (options.rangeSize === undefined) {
```
Comment (baywet) [inline src/tasks/LargeFileUploadTask.ts:164]:
```suggestion
		if (!options.rangeSize) {
```

File: src/tasks/LargeFileUploadTask.ts [hunk 17]
```diff
@@ -204,13 +219,14 @@ export class LargeFileUploadTask {
 	}
 
 	/**
+	 * @deprecated This function has been moved into FileObject interface.
 	 * @public
 	 * Slices the file content to the given range
 	 * @param {Range} range - The range value
 	 * @returns The sliced ArrayBuffer or Blob
 	 */
 	public sliceFile(range: Range): ArrayBuffer | Blob {
```
Comment (baywet) [inline src/tasks/LargeFileUploadTask.ts:228]: console warn maybe? so people not paying attention to compile time warning and/or not using typescript get a message in the console

File: src/tasks/LargeFileUploadTask.ts [hunk 18]
```diff
@@ -221,37 +237,51 @@ export class LargeFileUploadTask {
...
-				const err = new Error("Task with which you are trying to upload is already completed, Please check for your uploaded file");
-				err.name = "Invalid Session";
-				throw err;
-			}
-			const fileSlice = this.sliceFile(nextRange);
-			const rawResponse = await this.uploadSliceGetRawResponse(fileSlice, nextRange, this.file.size);
-			if (!rawResponse) {
-				throw new GraphClientError("Something went wrong! Large file upload slice response is null.");
-			}
+		const progressCallBack = this.options.progressCallBack;
```
Comment (baywet) [inline src/tasks/LargeFileUploadTask.ts:240]:
```suggestion
		const progressCallBack = this.options && this.options.progressCallBack;
```

File: src/tasks/LargeFileUploadTask.ts [hunk 19]
```diff
@@ -221,37 +237,51 @@ export class LargeFileUploadTask {
...
+					}
+					return uploadResult;
+				}
 
-			this.updateTaskStatus(res);
+				/* Handling the API issue where the case of Outlook upload response property -'nextExpectedRanges'  is not uniform.
+				 * https://github.com/microsoftgraph/msgraph-sdk-serviceissues/issues/39
+				 */
+				const res: UploadStatusResponse = {
+					expirationDateTime: responseBody.expirationDateTime,
```
Comment (baywet) [inline src/tasks/LargeFileUploadTask.ts:272]: the casing for that property differs as well from one workload to another

File: src/tasks/OneDriveLargeFileUploadTask.ts [hunk 20]
```diff
@@ -113,13 +143,14 @@ export class OneDriveLargeFileUploadTask extends LargeFileUploadTask {
 	 * @param {Client} client - The GraphClient instance
 	 * @param {string} requestUrl - The URL to create the upload session
 	 * @param {string} fileName - The name of a file to upload, (with extension)
+	 * @param {string} conflictBehavior - Conflict behaviour option. Default is 'rename'
 	 * @returns The promise that resolves to LargeFileUploadSession
 	 */
-	public static async createUploadSession(client: Client, requestUrl: string, fileName: string): Promise<any> {
+	public static async createUploadSession(client: Client, requestUrl: string, payloadOptions: OneDriveFileUploadSessionPayLoad): Promise<any> {
```
Comment (baywet) [inline src/tasks/OneDriveLargeFileUploadTask.ts:149]: replace any by session type

**Review by baywet — CHANGES_REQUESTED** [review]

File: docs/tasks/LargeFileUploadTask.md [hunk 21]
```diff
@@ -1,84 +1,142 @@
...
-	} catch (err) {
-		throw err;
-	}
+* To create the LargeFileUploadTask object you need to create -
+    *  An upload session as shown above.
+    *  A `FileObject` instance.
+
+**FileObject Interface**
+```typescript
+export interface FileObject {
```
[the remark this answers is not in the document]
Comment (nikithauc) [reply docs/tasks/LargeFileUploadTask.md:51]: https://developer.mozilla.org/en-US/docs/Web/API/File 
File is a JS built-in interface.

File: src/tasks/FileUploadUtil/Interfaces/IProgress.ts [hunk 22]
```diff
@@ -0,0 +1,26 @@
+/* eslint-disable @typescript-eslint/type-annotation-spacing */
+import { GraphClientError } from "../../../GraphClientError";
+import { Range } from "../../../Range";
+import { UploadResult } from "../UploadResult";
+
+/**
+ * Interface enabling progress handling with callbacks.
+ */
+export interface Progress {
```
[the remark this answers is not in the document]
Comment (nikithauc) [reply src/tasks/FileUploadUtil/Interfaces/IProgress.ts:9]: @zengin  How about `UploadProgressHandler`? 

`IProgressCallback`   and `IProgress` is use in Java and C#. So I thought of aligning close to that.
TypeScript does not use `I-` interface naming.

[the remark this answers is not in the document]
Comment (zengin) [reply src/tasks/FileUploadUtil/Interfaces/IProgress.ts:9]: Having `Progress` in the name is misleading IMO because it has an event handler defined inside this object for `Progress`. How about `UploadEventHandlers`?

`Progress` can also be used to represent the "full progress" as intended in the current state of the naming (e.g. `failure`, `uploading`, `uploaded` states in the progression of upload), but then we need to find a different name for that `uploading` state other than `progress`. Because it causes us to have calls like: `progressCallBack.progress`, similar to `error.error` we have discussed in other PRs.

File: src/index.ts [hunk 23]
```diff
@@ -26,11 +26,18 @@ export * from "./middleware/ChaosHandler";
 
 export * from "./tasks/LargeFileUploadTask";
 export * from "./tasks/OneDriveLargeFileUploadTask";
+export * from "./tasks/FileUploadUtil/FileObjectClasses/StreamUpload";
+export * from "./tasks/FileUploadUtil/FileObjectClasses/FileUpload";
+export * from "./tasks/FileUploadUtil/FileObjectClasses/StreamUpload";
+export * from "./tasks/FileUploadUtil/UploadResult";
+export * from "./tasks/FileUploadUtil/Interfaces/IProgress";
+export * from "./Range";
```
[the remark this answers is not in the document]
Comment (nikithauc) [reply src/index.ts]: Done

File: src/browser/index.ts [hunk 24]
```diff
@@ -21,7 +21,7 @@ export * from "../middleware/options/TelemetryHandlerOptions";
 export * from "../middleware/options/ChaosHandlerOptions";
 export * from "../middleware/options/ChaosStrategy";
 export * from "../middleware/ChaosHandler";
-
+export * from "../tasks/FileUploadUtil/FileObjectClasses/StreamUpload";
```
[the remark this answers is not in the document]
Comment (nikithauc) [reply src/browser/index.ts]: Done

File: src/tasks/FileUploadUtil/Interfaces/IProgress.ts (hunk 22 above)
[the remark this answers is not in the document]
Comment (nikithauc) [reply src/tasks/FileUploadUtil/Interfaces/IProgress.ts]: Done

File: test/common/tasks/LargeFileUploadTask.ts (hunk 4 above)
Comment (nikithauc) [reply test/common/tasks/LargeFileUploadTask.ts]: Done

File: docs/tasks/LargeFileUploadTask.md (hunk 6 above)
Comment (nikithauc) [reply docs/tasks/LargeFileUploadTask.md]: Done

File: src/tasks/LargeFileUploadTask.ts (hunk 19 above)
Comment (nikithauc) [reply src/tasks/LargeFileUploadTask.ts]: changed to `expirationDateTime: responseBody.expirationDateTime || responseBody.ExpirationDateTime`

File: src/tasks/LargeFileUploadTask.ts [hunk 25]
```diff
@@ -146,10 +150,21 @@ export class LargeFileUploadTask {
 	 */
 	public constructor(client: Client, file: FileObject, uploadSession: LargeFileUploadSession, options: LargeFileUploadTaskOptions = {}) {
 		this.client = client;
-		this.file = file;
+
+		if (!file.sliceFile) {
+			console.warn("Please pass a fileObject instance");
```
[the remark this answers is not in the document]
Comment (nikithauc) [reply src/tasks/LargeFileUploadTask.ts]: Changed the warning.

[the remark this answers is not in the document]
Comment (nikithauc) [reply src/tasks/LargeFileUploadTask.ts]: This checks if the sliceFlice function property is present. This check applies on a JS code as it is not typed and does not have interfaces.  As sliceFile is a new property in the existing `FileObject` interface, this will throw a runtime error if the JS code uses the old `FileObject` structure.

File: docs/tasks/LargeFileUploadTask.md [hunk 26]
```diff
@@ -1,84 +1,142 @@
...
 ```
+The Microsoft Graph JavaScript Client SDK provides two implementions -
+1. StreamUpload - Supports Node.js stream upload
+    ```typescript
+    
+    import StreamUpload from "@microsoft/microsoft-graph-client";
+    import * as fs from "fs";
+    
+    const fileName = "<FILE_NAME>";
+	const stats = fs.statSync(`./test/sample_files/${fileName}`);
```
[the remark this answers is not in the document]
Comment (nikithauc) [reply docs/tasks/LargeFileUploadTask.md]: Corrected the spacing. The doc style goes off when I update from my VS Code set up. The style looks fine in VS Code. Will check.

File: docs/tasks/LargeFileUploadTask.md (hunk 7 above)
Comment (nikithauc) [reply docs/tasks/LargeFileUploadTask.md]: documented the generic interface here. The point is to specify the generic nature of the content property enabling custom implementation as well.

File: src/tasks/FileUploadUtil/Interfaces/IProgress.ts (hunk 13 above)
Comment (nikithauc) [reply src/tasks/FileUploadUtil/Interfaces/IProgress.ts]: unknown can be anything. Changed the name to `extraCallbackParam`. The extra param could be anything such as an object/type specific to the user application or an array of unknown.

File: src/tasks/LargeFileUploadTask.ts (hunk 14 above)
Comment (nikithauc) [reply src/tasks/LargeFileUploadTask.ts]: Done

File: src/tasks/LargeFileUploadTask.ts (hunk 15 above)
Comment (nikithauc) [reply src/tasks/LargeFileUploadTask.ts]: The code has changed. The outermost try-catch is removed. So the source error will be thrown at that line.

File: src/tasks/LargeFileUploadTask.ts (hunk 17 above)
Comment (nikithauc) [reply src/tasks/LargeFileUploadTask.ts:229]: Done

File: src/tasks/FileUploadUtil/Interfaces/IProgress.ts (hunk 13 above)
Comment (baywet) [reply src/tasks/FileUploadUtil/Interfaces/IProgress.ts]: thanks! yeah the plural name was leading me to think it should be an array. If a parameter/property needs to be an array of something, but we don't know what, it's always good to have an array of unknown as the type instead of just unknown. It tells the consumer we're at least expecting an array and we get transpile time validation for the array prototype (the "first level of the object model"). Better than nothing :)

File: samples/node/main.js [hunk 27]
```diff
@@ -12,24 +7,119 @@ const secrets = require("./secrets");
...
+                console.log("File Uploaded Successfully.!!");
+            })
+            .catch((error) => {
+                throw error;
+            });
+    });
+}
+async function oneDriveLargeFileUpload1(client, file, fileName) {
+    try {
+        let options = {
```
Comment (baywet) [inline samples/node/main.js]:
```suggestion
        const options = {
```

File: samples/node/main.js [hunk 28]
```diff
@@ -12,24 +7,119 @@ const secrets = require("./secrets");
...
+
+    let fileName = "testpd.pdf";
+    let size = "";
+    var stats = fs.statSync("testpd.pdf")
+   
+        console.log(stats.fileName);
+   
+    const file = new MicrosoftGraph.StreamUpload(fs.createReadStream("./testpd.pdf"),fileName, stats.size);
+    try {
+        let options = {
```
Comment (baywet) [inline samples/node/main.js]:
```suggestion
        const options = {
```

File: samples/node/main.js [hunk 29]
```diff
@@ -12,24 +7,119 @@ const secrets = require("./secrets");
...
+                console.log(response);
+                console.log("File Uploaded Successfully.!!");
+            })
+            .catch((error) => {
+                throw error;
+            });
+    });
+}
+async function oneDriveLargeFileUpload2(client, file, fileName) {
+    var stats = fs.statSync("./test.txt")
```
Comment (baywet) [inline samples/node/main.js]:
```suggestion
    const stats = fs.statSync("./test.txt")
```

File: samples/node/main.js [hunk 30]
```diff
@@ -12,24 +7,119 @@ const secrets = require("./secrets");
...
+uploadFile();
+
+
+//file upload test 
+function uploadFile2() {
+    fs.readFile("./test.txt", {}, function(err, file) {
+        if (err) {
+            throw err;
+        }
+        let fileName = "test.txt";
```
Comment (baywet) [inline samples/node/main.js]:
```suggestion
        const fileName = "test.txt";
```

File: samples/node/main.js [hunk 31]
```diff
@@ -12,24 +7,119 @@ const secrets = require("./secrets");
...
+        console.log(err);
+    }
+}
+//uploadFile1();
+
+async function uploadFile() {
+
+    let fileName = "testpd.pdf";
+    let size = "";
+    var stats = fs.statSync("testpd.pdf")
```
Comment (baywet) [inline samples/node/main.js]:
```suggestion
    const stats = fs.statSync(fileName)
```

File: samples/node/main.js [hunk 32]
```diff
@@ -12,24 +7,119 @@ const secrets = require("./secrets");
...
+   
+        console.log(stats.fileName);
+   
+    const file = new MicrosoftGraph.StreamUpload(fs.createReadStream("./testpd.pdf"),fileName, stats.size);
```
Comment (baywet) [inline samples/node/main.js]:
```suggestion
    const file = new MicrosoftGraph.StreamUpload(fs.createReadStream(fileName),fileName, stats.size);
```

File: samples/node/main.js [hunk 33]
```diff
@@ -12,24 +7,119 @@ const secrets = require("./secrets");
...
+    } catch (err) {
+        console.log(err);
+    }
+}
+//uploadFile1();
+
+async function uploadFile() {
+
+    let fileName = "testpd.pdf";
+    let size = "";
```
Comment (baywet) [inline samples/node/main.js]: is this used at all?

File: samples/node/main.js [hunk 34]
```diff
@@ -12,24 +7,119 @@ const secrets = require("./secrets");
...
+    },
 });
 
+
+function uploadFile1() {
+    fs.readFile("./testpd.pdf", {}, function(err, file) {
+        if (err) {
+            throw err;
+        }
+        let fileName = "testpd.pdf";
```
Comment (baywet) [inline samples/node/main.js]:
```suggestion
```

File: samples/node/main.js [hunk 35]
```diff
@@ -12,24 +7,119 @@ const secrets = require("./secrets");
...
+    defaultVersion: "v1.0",
+    debugLogging: true,
+    authProvider: (done) => {
+        done(null, secrets.accessToken);
+    },
 });
 
+
+function uploadFile1() {
+    fs.readFile("./testpd.pdf", {}, function(err, file) {
```
Comment (baywet) [inline samples/node/main.js]:
```suggestion
    const fileName = "testpd.pdf";
    fs.readFile(fileName, {}, function(err, file) {
```

File: samples/node/main.js [hunk 36]
```diff
@@ -12,24 +7,119 @@ const secrets = require("./secrets");
...
+            })
+            .catch((error) => {
+                throw error;
+            });
+    });
+}
+async function oneDriveLargeFileUpload2(client, file, fileName) {
+    var stats = fs.statSync("./test.txt")
+    try {
+        let options = {
```
Comment (baywet) [inline samples/node/main.js]:
```suggestion
        const options = {
```

File: samples/node/main.js [hunk 37]
```diff
@@ -12,24 +7,119 @@ const secrets = require("./secrets");
...
+        };
+        const fileObj = new MicrosoftGraph.FileUpload(file,fileName, stats.size);
+        const uploadTask = await MicrosoftGraph.OneDriveLargeFileUploadTask.createTaskWithFileObject(client, fileObj, options);
+        const response = await uploadTask.upload();
+        return response;
+    } catch (err) {
+        console.log(err);
+    }
+}
+//uploadFile2();
```
Comment (baywet) [inline samples/node/main.js]: remove commented

File: src/tasks/LargeFileUploadTask.ts [hunk 38]
```diff
@@ -198,13 +212,14 @@ export class LargeFileUploadTask {
 	}
 
 	/**
+	 * deprecated
```
Comment (baywet) [inline src/tasks/LargeFileUploadTask.ts]: provide a reason why it's deprecated

File: src/tasks/LargeFileUploadTask.ts [hunk 39]
```diff
@@ -243,13 +266,15 @@ export class LargeFileUploadTask {
 	 * @param {number} totalSize - The total size of a complete file
 	 */
 	public async uploadSlice(fileSlice: ArrayBuffer | Blob | File, range: Range, totalSize: number): Promise<any> {
-		return await this.client
+		console.log("here");
```
Comment (baywet) [inline src/tasks/LargeFileUploadTask.ts]: remove

File: src/tasks/LargeFileUploadTask.ts [hunk 40]
```diff
@@ -243,13 +266,15 @@ export class LargeFileUploadTask {
 	 * @param {number} totalSize - The total size of a complete file
 	 */
 	public async uploadSlice(fileSlice: ArrayBuffer | Blob | File, range: Range, totalSize: number): Promise<any> {
```
Comment (baywet) [inline src/tasks/LargeFileUploadTask.ts]: unknown instead? or object?

File: src/tasks/OneDriveLargeFileUploadTask.ts [hunk 41]
```diff
@@ -91,16 +105,29 @@ export class OneDriveLargeFileUploadTask extends LargeFileUploadTask {
...
+	 * @static
+	 * @async
+	 * Creates a OneDriveLargeFileUploadTask
+	 * @param {Client} client - The GraphClient instance
+	 * @param {FileObject} file - FileObject instance
+	 * @param {OneDriveLargeFileUploadOptions} options - The options for upload task
+	 * @returns The promise that will be resolves to OneDriveLargeFileUploadTask instance
+	 */
+	public static async createTaskWithFileObject(client: Client, fileObject: FileObject, options: OneDriveLargeFileUploadOptions) {
 		const requestUrl = OneDriveLargeFileUploadTask.constructCreateSessionUrl(options.fileName, options.path);
```
Comment (baywet) [inline src/tasks/OneDriveLargeFileUploadTask.ts:125]: defend against null options

File: src/tasks/OneDriveLargeFileUploadTask.ts [hunk 42]
```diff
@@ -113,13 +140,14 @@ export class OneDriveLargeFileUploadTask extends LargeFileUploadTask {
...
 	 * @returns The promise that resolves to LargeFileUploadSession
 	 */
-	public static async createUploadSession(client: Client, requestUrl: string, fileName: string): Promise<any> {
+	public static async createUploadSession(client: Client, requestUrl: string, payloadOptions: OneDriveFileUploadSessionPayLoad): Promise<any> {
 		const payload = {
 			item: {
-				"@microsoft.graph.conflictBehavior": "rename",
-				name: fileName,
+				"@microsoft.graph.conflictBehavior": payloadOptions.conflictBehavior || 'rename',
+				name: payloadOptions.fileName,
```
Comment (baywet) [inline src/tasks/OneDriveLargeFileUploadTask.ts:153]:
```suggestion
				name: payloadOptions?.fileName,
```

**Review by baywet — CHANGES_REQUESTED** [review]

**Comment by baywet** [comment]
I missed one commit in my previous review, sorry about that, resolved the things are are already resolved. Only a few things left :)

File: src/tasks/FileUploadUtil/Interfaces/IProgress.ts (hunk 13 above)
Comment (nikithauc) [reply src/tasks/FileUploadUtil/Interfaces/IProgress.ts]: Thank you for the reasoning and I agree that if the `extraCallbackParam` was only expecting an array, then it should be defined explicitly.

**Comment by nikithauc** [comment]
> I missed one commit in my previous review, sorry about that, resolved the things are are already resolved. Only a few things left :)

Thank you for the review! I liked the idea to use generics.

**Review by baywet — APPROVED** [review]

**Review by zengin — APPROVED** [review]
LGTM. Thanks for taking the proposed changes.
